version: "3.8"

services:
  # DynamoDB Local for development
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: audio-slide-dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - dynamodb-data:/home/dynamodblocal/data
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data"
    user: root
    networks:
      - audio-slide-network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s http://localhost:8000 | grep -q 'MissingAuthenticationToken' || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 3

  # DynamoDB Admin Web UI
  dynamodb-admin:
    image: aaronshaf/dynamodb-admin:latest
    container_name: audio-slide-dynamodb-admin
    ports:
      - "8002:8001"
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb-local:8000
      - AWS_REGION=ap-northeast-1
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
    depends_on:
      dynamodb-local:
        condition: service_healthy
    networks:
      - audio-slide-network

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_API_BASE_URL: http://localhost:8080/api
    container_name: audio-slide-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - audio-slide-network
    restart: unless-stopped

  # Backend API service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: audio-slide-backend
    ports:
      - "8080:8080"
    environment:
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
      - AWS_REGION=ap-northeast-1
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - PORT=8080
    depends_on:
      dynamodb-local:
        condition: service_healthy
    networks:
      - audio-slide-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  # DynamoDB table initialization service (manual setup required)
  # Run this command manually after startup:
  # docker run --rm --network app_audio-slide-network -e AWS_ACCESS_KEY_ID=dummy -e AWS_SECRET_ACCESS_KEY=dummy -e AWS_DEFAULT_REGION=ap-northeast-1 amazon/aws-cli:latest dynamodb create-table --endpoint-url http://dynamodb-local:8000 --region ap-northeast-1 --table-name Quiz --attribute-definitions AttributeName=PK,AttributeType=S AttributeName=SK,AttributeType=S AttributeName=category,AttributeType=S AttributeName=id,AttributeType=S --key-schema AttributeName=PK,KeyType=HASH AttributeName=SK,KeyType=RANGE --global-secondary-indexes IndexName=category-id-index,KeySchema=[{AttributeName=category,KeyType=HASH},{AttributeName=id,KeyType=RANGE}],Projection={ProjectionType=ALL},ProvisionedThroughput={ReadCapacityUnits=5,WriteCapacityUnits=5} --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5

volumes:
  dynamodb-data:
    driver: local

networks:
  audio-slide-network:
    driver: bridge
