# ==================================================
# CI Workflow - Audio Slide App
# ==================================================
# developブランチにマージされた際に実行されるCI（継続的インテグレーション）
# - バックエンド（Go）のテストのみを実行
# - app/backend に変更がある場合のみ実行

name: CI - Backend Test on Develop

# ワークフロー実行トリガー
on:
  push:
    branches: [develop] # developブランチへのプッシュ時
  pull_request:
    branches: [develop] # developブランチへのプルリクエスト時
    types: [opened] # PR作成時のみ実行
    paths: # app/backendに変更がある場合のみ実行
      - "app/backend/**"
      - ".github/workflows/ci.yml"

# 環境変数
env:
  GO_VERSION: "1.22"

jobs:
  # ==================================================
  # バックエンドテストジョブ
  # ==================================================
  # Go/Ginアプリケーションのテストを実行
  backend-test:
    runs-on: ubuntu-latest

    # DynamoDB Localサービスを起動
    services:
      dynamodb-local:
        image: amazon/dynamodb-local:latest
        ports:
          - 8000:8000
        options: >-
          --health-cmd "curl -f http://localhost:8000 || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('app/backend/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        working-directory: ./app/backend
        run: go mod download

      - name: Run tests
        working-directory: ./app/backend
        env:
          DYNAMODB_ENDPOINT: http://localhost:8000
          AWS_REGION: ap-northeast-1
          AWS_ACCESS_KEY_ID: dummy
          AWS_SECRET_ACCESS_KEY: dummy
        run: |
          go test -v ./...
